-- Setup script for the Hello Snowflake! app.
CREATE APPLICATION ROLE IF NOT EXISTS app_public;
CREATE SCHEMA IF NOT EXISTS core;
GRANT USAGE ON SCHEMA core TO APPLICATION ROLE app_public;

CREATE OR REPLACE PROCEDURE CORE.HELLO()
  RETURNS STRING
  LANGUAGE SQL
  EXECUTE AS OWNER
  AS
  BEGIN
    RETURN 'Hello Snowflake!';
  END;

  GRANT USAGE ON PROCEDURE core.hello() TO APPLICATION ROLE app_public;

  CREATE OR ALTER VERSIONED SCHEMA code_schema;
  GRANT USAGE ON SCHEMA code_schema TO APPLICATION ROLE app_public;

  CREATE VIEW IF NOT EXISTS code_schema.accounts_view
    AS SELECT ID,NAME,VALUES
    FROM shared_data.accounts;

  GRANT SELECT ON VIEW code_schema.accounts_view TO APPLICATION ROLE app_public;